### ISSUE TITLE
Think  a Name

### ISSUE THREAD

**Issue by thesmallstar** [thesmallstar/CheckMate#3]

**Comment by Archies11** [comment]
The name that i think is barry sootable ij   CHECKMATE !!!!!!!!!
bcoz this is a pun... mate is a frand so check mate is a frand that halps in chacking . also ckeckmate means the prablame ij salved

**Comment by Archies11** [comment]
PS: I know and understand english. This is just a joke. Please don't judge.
HALLELUJAHHHHH

**Comment by thesmallstar** [comment]
Yus I de egree it ij a nuice nem let uz finel it.

Checkmeeeeeetttt

**Comment by roshnidesigns** [comment]
can we design a logo for this...?

**Comment by thesmallstar** [comment]
@Archies11  @hermione-18  checkmate final then?

**Comment by thesmallstar** [comment]
> can we design a logo for this...?

If it is final,  we can start on the logo

**Comment by Archies11** [comment]
I will design the logo

**Comment by roshnidesigns** [comment]
we will ;)

**Comment by thesmallstar** [comment]
@Archies11 @hermione-18  CheckMate is the final then. In the.env file make sure you change checkme to CheckMate. 
Closing the issue.
