### ISSUE TITLE
Design a logo 

### ISSUE THREAD

**Issue by thesmallstar** [thesmallstar/CheckMate#5]
Archisha and roshni please work on this :)

**Comment by roshnidesigns** [comment]
https://github.com/hermione-18/logo.git

**Comment by thesmallstar** [comment]
Looks good, Great!

**Comment by roshnidesigns** [comment]
I'm designing another one...if it's not good then this one is final!

**Comment by roshnidesigns** [comment]
have look at this..second one
https://github.com/hermione-18/logo.git

**Comment by roshnidesigns** [comment]
so we are done with the logo part ^_^

**Comment by thesmallstar** [comment]
Great!
